{
  # finetuning option
  "finetune": false,

  # init methods
  "init_method": "small_init",
  "output_layer_init_method": "wang_init",

  # optimizer settings
  "optimizer": {
    "type": "Adam",
    "params": {
     "lr": 0.0002,
     "betas": [0.9, 0.95],
     "eps":  1.0e-8,
    }
  },
  "min_lr": 0.00002,
  "override_lr_scheduler": true,

  # for all zero_optimization options, see https://www.deepspeed.ai/docs/config-json/#zero-optimizations-for-fp16-training
   "zero_optimization": {
   "stage": 1,
   "allgather_partitions": true,
   "allgather_bucket_size": 500000000,
   "overlap_comm": true,
   "reduce_scatter": true,
   "reduce_bucket_size": 500000000,
   "contiguous_gradients": true,
  },

  # batch / data settings
  "train_batch_size": 1024,
  "gradient_accumulation_steps": 1,
  #"train_micro_batch_size_per_gpu": 4,
  "data_impl": "mmap",

  # activation checkpointing
  "checkpoint_activations": true,
  "checkpoint_num_layers": 1,
  "partition_activations": true,
  "synchronize_each_layer": true,

  # regularization
  "gradient_clipping": 1.0,
  "weight_decay": 0.1,
  "hidden_dropout": 0,
  "attention_dropout": 0,

  # precision settings
  "precision": "bfloat16",

  # misc. training settings
  "train_iters": 100,
  "lr_decay_iters": 10,
  "distributed_backend": "nccl",
  "lr_decay_style": "cosine",
  "warmup": 0.1,
  "checkpoint_factor": 10000,
  "eval_interval": 50,
  "eval_iters": 10,
  "num_workers": 0,
}