# GPT-2 pretraining setup
{
  # parallelism settings ( you will want to change these based on your cluster setup, ideally scheduling pipeline stages
  # across the node boundaries )
  "pipe_parallel_size": 0,
  "model_parallel_size": 1,

  # model settings
  "num_layers": 12,
  "hidden_size": 768,
  "num_attention_heads": 12,
  "seq_length": 4096,
  "max_position_embeddings": 4096,
  "norm": "layernorm",
  "pos_emb": "rotary",
  "no_weight_tying": true,
  "gpt_j_residual": false,
  "output_layer_parallelism": "column",

  #flash_attention - value = num_layers
  #"attention_config": [[["flash"], 12]],

  # these should provide some speedup but takes a while to build, set to true if desired
  "scaled_upper_triang_masked_softmax_fusion": true,
  "bias_gelu_fusion": false,
  "rope_fusion": false,
  "layernorm_fusion": false,

  # init methods
  "init_method": "small_init",
  "output_layer_init_method": "wang_init",

  # optimizer settings
  "optimizer":
    {
      "type": "Adam",
      "params": { "lr": 0.0006, "betas": [0.9, 0.95], "eps": 1.0e-8 },
    },
  "min_lr": 0.00006,

  # for all zero_optimization options, see https://www.deepspeed.ai/docs/config-json/#zero-optimizations-for-fp16-training
  "zero_optimization":
    {
      "stage": 1,
      "allgather_partitions": True,
      "allgather_bucket_size": 500000000,
      "overlap_comm": True,
      "reduce_scatter": false,
      "reduce_bucket_size": 500000000,
      "contiguous_gradients": True,
    },

  # batch / data settings
  "train_micro_batch_size_per_gpu": 4,
  "data_impl": "mmap",

  # activation checkpointing
  "checkpoint_activations": true,
  "checkpoint_num_layers": 1,
  "partition_activations": true,
  "synchronize_each_layer": true,

  # regularization
  "gradient_clipping": 1.0,
  "weight_decay": 0.1,
  "hidden_dropout": 0.0,
  "attention_dropout": 0.9,

  # precision settings
  "precision": "bfloat16",
  "fp32_allreduce": true,

  # misc. training settings
  "train_iters": 1000,
  "lr_decay_iters": 1000,
  "distributed_backend": "nccl",
  "lr_decay_style": "cosine",
  "warmup": 0.01,
  "eval_interval": 100,
  "eval_iters": 10,
  "num_workers": 0,

  # logging
  "log_interval": 100,
  "steps_per_print": 10,
  "tensorboard_dir": "logs/tb/",
  "data_path": "data/enwik8/enwik8_text_document",
  "vocab_file": "data/gpt2-vocab.json",
  "merge_file": "data/gpt2-merges.txt",

  #Deepspeed misc
  "wall_clock_breakdown": false,
  "tensorboard":
    {
      "enabled": false,
      "output_path": "logs/tb/",
    },
  "comms_logger":
    { "enabled": false, "verbose": false, "prof_all": true, "debug": False },
}
